#index:
#    path: /
#    controller: App\Controller\DefaultController::index

program_index:
    path: /program
    controller: App\Controller\ProgramController::index

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::index